version: "3"
services:
  wiremock:
    ipc: host ## Prevent Docker Crash in Cypress (https://github.com/cypress-io/cypress/issues/350)
    networks:
      cypress:
    image: docker-externals.artifacts.dbccloud.dk/wiremock:3.3.1
    volumes:
      - "./wiremock:/home/wiremock:ro"
  web:
    ipc: host ## Prevent Docker Crash in Cypress (https://github.com/cypress-io/cypress/issues/350)
    image: "${IMAGE_NAME}"
    networks:
      cypress:
    environment:
      - NODE_ENV=production
      - ENABLE_STORYBOOK=0
      - STORYBOOK_PORT=4000
      - PORT=3000
      - NEXTAUTH_URL=http://web:3000
      - NEXTAUTH_SECRET=a_long_next_auth_secret
      - APIKEYS={"010100":{"apikey":"pass"},"820030":{"apikey":"pass"},"test":{"apikey":"test"},"810010":{"apikey":"pass"}}
      - CLIENT_ID=a_client_id
      - CLIENT_SECRET=a_client_secret
      - FILESTORE_URL=http://wiremock:8080
    depends_on:
      - wiremock
    command: npm run start
  e2e:
    ipc: host ## Prevent Docker Crash in Cypress (https://github.com/cypress-io/cypress/issues/350)
    networks:
      cypress:
    image: docker-dbc.artifacts.dbccloud.dk/cypress:latest
    volumes:
      - "./e2e/cypress:/app/cypress"
      - "./e2e/cypress.config.js:/app/cypress.config.js"
    depends_on:
      - web
    environment:
      - CYPRESS_baseUrl=http://web:3000
      - CYPRESS_nextjsBaseUrl=http://web:3000
      - ELECTRON_ENABLE_LOGGING=0
      - BROWSER=electron
      - CONFIG_FILE=cypress.config.js
      - CYPRESS_FOLDER=/app/cypress
networks:
  cypress:
    driver: bridge
