version: "3"
services:
  wiremock:
    ipc: host ## Prevent Docker Crash in Cypress (https://github.com/cypress-io/cypress/issues/350)
    image: wiremock/wiremock
    volumes:
      - "./wiremock:/home/wiremock:ro"
  web:
    ipc: host ## Prevent Docker Crash in Cypress (https://github.com/cypress-io/cypress/issues/350)
    image: "${IMAGE_NAME}"
    environment:
      - NODE_ENV=production
      - ENABLE_STORYBOOK=1
      - STORYBOOK_PORT=4000
      - PORT=3000
      - NEXTAUTH_URL=http://web:3000
      - NEXTAUTH_SECRET=a_long_next_auth_secret
      - APIKEYS={"010100":{"apikey":"pass"},"820030":{"apikey":"pass"},"test":{"apikey":"test"},"810010":{"apikey":"pass"}}
      - CLIENT_ID=a_client_id
      - CLIENT_SECRET=a_client_secret
      - FILESTORE_URL=http://wiremock:8080
    command: npm run start
  e2e:
    ipc: host ## Prevent Docker Crash in Cypress (https://github.com/cypress-io/cypress/issues/350)
    image: docker-dbc.artifacts.dbccloud.dk/cypress:latest
    volumes:
      - "./e2e:/app/e2e"
    depends_on:
      - web
    environment:
      - CYPRESS_baseUrl=http://web:3000
      - CYPRESS_nextjsBaseUrl=http://web:3000
      - ELECTRON_ENABLE_LOGGING=0
